NewMap7_MapScripts::
	.byte 0

Script_MtEmberfallFallExteriorSign::
    lock
    faceplayer
    msgbox Text_MtEmberfallFallExteriorSign, MSGBOX_DEFAULT
    release
    end

Text_MtEmberfallFallExteriorSign:
    .string "{COLOR BLUE}Mt. Emberfall\n"

Script_MtEmberfallFallExteriorMan1::
    lock
    faceplayer
    msgbox Text_MtEmberfallFallExteriorMan1, MSGBOX_DEFAULT
    release
    end

Text_MtEmberfallFallExteriorMan1:
    .string "I'm on my way to Onsen City.\n"
    .string "Quite a distance from here, but I\l"
    .string "should be alright.$"

Script_MtEmberfallFallExteriorMan2::
    lock
    faceplayer
    msgbox Text_MtEmberfallFallExteriorMan2, MSGBOX_DEFAULT
    release
    end

Text_MtEmberfallFallExteriorMan2:
    .string "This mountain is one tough climb.\n"
    .string "Good excercise early in the morning.$"

Script_MtEmberfallFallExteriorWoman1::
    lock
    faceplayer
    msgbox Text_MtEmberfallFallExteriorWoman1, MSGBOX_DEFAULT
    release
    end

Text_MtEmberfallFallExteriorWoman1:
    .string "I love coming here to pick flowers.\n"
    .string "The colors are just so pretty.$"

Script_MtEmberfallFallExteriorWoman2::
    lock
    faceplayer
    msgbox Text_MtEmberfallFallExteriorWoman2, MSGBOX_DEFAULT
    release
    end

Text_MtEmberfallFallExteriorWoman2:
    .string "Look at these flowers.\n"
    .string "They are both blue and purple!$"
