HallowSparkHouse12F_MapScripts::
	.byte 0

Script_HallowSparkHouse1Kid1::
    lock
    faceplayer
    msgbox Text_HallowSparkHouse1Kid1, MSGBOX_DEFAULT
    release
    end

Text_HallowSparkHouse1Kid1:
    .string "You look like you need some pokéballs.\n"
    .string "A birdie told me the Pokémart is\l"
    .string "giving them away.\l"
    .string "You should go check them out.$"
    
Script_HallowSparkHouse1Kid2::
    lock
    faceplayer
    msgbox Text_HallowSparkHouse1Kid2, MSGBOX_DEFAULT
    release
    end

Text_HallowSparkHouse1Kid2:
    .string "Hey!\n"
    .string "Who allowed you up here?\l"
    .string "My dad?"
    .string "Man, he always does the most annoying\l"
    .string "things, I tell you.$"

Script_HallowSparkHouse1Kid3::
    lock
    faceplayer
    msgbox Text_HallowSparkHouse1Kid3, MSGBOX_DEFAULT
    release
    end

Text_HallowSparkHouse1Kid3:
    .string "You suck$"
