OnsenHouse2_MapScripts::
	.byte 0

Script_OnsenCityHouse3Man1::
    lock
    faceplayer
    msgbox Text_OnsenCityHouse3Man1, MSGBOX_DEFAULT
    release
    end

Text_OnsenCityHouse3Man1:
    .string "All this land came from a single\n"
    .string "volcano: Mt. Emberfall.\l"
    .string "that is crazy.$"

Script_OnsenCityHouse3Woman1::
    lock
    faceplayer
    msgbox Text_OnsenCityHouse3Woman1, MSGBOX_DEFAULT
    release
    end

Text_OnsenCityHouse3Woman1:
    .string "The developers should've put a gym\n"
    .string "here.\l"
    .string "A fire-type gym here would be...HEAT!\l"
    .string "HAHAHAHA I'm so funny, right?$"
    
Script_OnsenCityHouse3Daughter1::
    lock
    faceplayer
    msgbox Text_OnsenCityHouse3Daughter1, MSGBOX_DEFAULT
    release
    end

Text_OnsenCityHouse3Daughter1:
    .string "I can't wait to get out of here as\n"
    .string "soon as I turn 18.$"
