gText_Birch_Welcome::
	.string "Hi! Sorry if you were waiting!\p"
	.string "Welcome to the world of Pokémon!\p"
	.string "My name is {COLOR BLUE}Pine{COLOR DARK_GRAY}.\p"
	.string "But everyone knows me as the Pokémon\n"
	.string "Professor of the region {COLOR RED}Hehamayto{COLOR DARK_GRAY},\l"
    .string "or {COLOR RED}Heto{COLOR DARK_GRAY} for short.\p"
    .string "\n"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “Pokémon.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "The world we live in is widely\n"
	.string "inhabited by creatures known as\l"
    .string "Pokémon.\p"
	.string "We humans live alongside Pokémon,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite Pokémon being an intergral\n"
    .string "part of everyday life today, we don't\l"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding Pokémon.\p"
	.string "To unravel the mysteries on Pokémon,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who lives in\n"
	.string "my town of residence: {COLOR BLUE}Pearl Town{COLOR DARK_GRAY}.\l"
	.string "I've heard of you from your mom!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold!\p"
	.string "Take courage, and leap into this\n"
	.string "new world of Pokémon where dreams\l"
	.string "become reality!\p"
	.string "Come visit me in my Pokémon Lab\n"
	.string "when you wake up.\p"
	.string "$"
