OnsenMart_MapScripts::
	.byte 0

Script_OnsenCityMartCustomer1::
    lock
    msgbox Text_OnsenCityMartCustomer1, MSGBOX_DEFAULT
    release
    end

Text_OnsenCityMartCustomer1:
    .string "Man,\n"
    .string "it's so hard to choose what items to\l"
    .string "buy.\p"
    .string "Just like how it's so hard to choose\l"
    .string "if I belong to {SHADOW DARK_GRAY}Toemayto{SHADOW LIGHT_GRAY} or {SHADOW DARK_GRAY}Hehamayto{SHADOW LIGHT_GRAY}.\p"
    .string "{FONT_SMALL_NARROW}I should not have said that.$"
