EverbloomHouse2_MapScripts::
	.byte 0

Script_EverbloomHouse21::
    lock
    faceplayer
    msgbox Text_EverbloomHouse21, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse21:
    .string "My wife is Flora!\n"
    .string "The gym leader of this city!\l"
    .string "Since she’s the breadwinner here, my\l"
    .string "role has been reduced to being a\l"
    .string "househusband...$"

Script_EverbloomHouse22::
    lock
    faceplayer
    msgbox Text_EverbloomHouse22, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse22:
    .string "Mommy’s really strong!\n"
    .string "I bet she’d beat you up!$"
