@ New Trainers and their scripts -- put each trainer script here instead of the 
@ actual map script file (leave preexisting trainers alone)

@ format:

@ (NAME OF PlACE) Trainer Scripts (keep the '@' symbol in order to keep this header a comment)

@ put trainer scripts below (without the '@' symbol so agbcc can actually read these scripts)

@ example:

@ ---- Hetonian Desert Trainer Scripts ----
@ (example scripts)...




