EverbloomHouse3_MapScripts::
	.byte 0

Script_EverbloomHouse31::
    lock
    faceplayer
    msgbox Text_EverbloomHouse31, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse31:
    .string "Everbloom’s technically classified\n"
    .string "as a city, but the feel of it is more\l"
    .string "close to that of a town.\l"
    .string "There are trees scattered everywhere,\l"
    .string "and it doesn’t really give off an\l"
    .string "industrial vibe.$"

Script_EverbloomHouse32::
    lock
    faceplayer
    msgbox Text_EverbloomHouse32, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse32:
    .string "The combination of plants, sunshine,\n"
    .string "and clean air is what makes Everbloom\l"
    .string "an ever blooming city.\p"
    .string "That was a good pun, wasn’t it?$"
