EverbloomHouse5_MapScripts::
	.byte 0

Script_EverbloomHouse51::
    lock
    faceplayer
    msgbox Text_EverbloomHouse51, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse51:
    .string "YOWZA!\n"
    .string "That cup of coffee burnt the roof of\l"
    .string "my mouth.$"

Script_EverbloomHouse52::
    lock
    faceplayer
    msgbox Text_EverbloomHouse52, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse52:
    .string "Mai Sakurajima is so hot...$"

Script_EverbloomHouse53::
    lock
    faceplayer
    msgbox Text_EverbloomHouse53, MSGBOX_DEFAULT
    release
    end

Text_EverbloomHouse53:
    .string "My brother’s girlfriend dumped him\n"
    .string "because she didn’t wanna rewatch\l"
    .string "Bunny Girl Senpai for the 12th time\l"
    .string "in a row.\l"
    .string "I don’t understand what’s wrong with\l"
    .string "my brother’s hobby, I’m glad she left.$"
