SilverstoneHouse1A_MapScripts::
	.byte 0

Script_SilverstoneHouse1Man1::
    lock
    faceplayer
    msgbox Text_SilverstoneHouse1Man1, MSGBOX_DEFAULT
    release
    end

Text_SilverstoneHouse1Man1:
    .string "These are objectively the top 5\n"
    .string "greatest players in NBA history:\l"
    .string "1. Stephen Curry\l"
    .string "2. Stephen Curry\l"
    .string "3. Slepen Blurry\l"
    .string "4. Step Flurry\l"
    .string "5. Chef Curry$"

Script_SilverstoneHouse1Man2::
    lock
    faceplayer
    msgbox Text_SilverstoneHouse1Man2, MSGBOX_DEFAULT
    release
    end

Text_SilverstoneHouse1Man2:
    .string "These are objectively the top 5\n"
    .string "greatest players in NBA history:\l"
    .string "1. Brian Scalabrine\l"
    .string "2. Brian Scalabrine\l"
    .string "3. Blian Scarabrine\l"
    .string "4. The White Mamba\l"
    .string "5. 'I'm closer to LeBron then you are\l"
    .string "to me' - The G.O.A.T$"
